# @see http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-external-config
# @see https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-yaml

app:
    name: gradle-tdd
    description: Simple Java Web project create to proof that is possible work with TDD/Java with simple way

server:
    port: 0

---

spring:
    profiles: dev

server:
    port: 8080

---

 spring:
    profiles: test

---

spring:
    profiles: prod

server:
    port: 8081
