# @see http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-external-config
# @see https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-yaml
# @see https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# for validate Yaml files @see http://yaml-online-parser.appspot.com/

app:
    name: gradle-tdd
    description: Simple Java Web project create to proof that is possible work with TDD/Java with simple way

spring:
    application:
        name: gradle-tdd
    profiles:
        active: "@profile@"
    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: validate
            hbm2ddl:
              auto: validate
        properties:
            hibernate:
                hbm2ddl:
                    auto: validate
    resources:
        cachePeriod: 31556926
#        staticPathPattern: /**
#        staticLocations: [ "classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/" ]

flyway:
    baseline-on-migrate: true
    locations: "@flywayLocations@"

server:
    port: 0

---

spring:
    profiles: dev
    h2:
        console:
            enabled: true

server:
    port: 8080

---

spring:
    profiles: test
---

spring:
    profiles: demo

server:
    port: 8080

---

spring:
    profiles: prod

server:
    port: 8081
