# @see http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-external-config
# @see https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-yaml
# @see https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# for validate Yaml files @see http://yaml-online-parser.appspot.com/

spring:
    application:
        name: survey-caiena
    profiles:
        active: "@profile@"
    datasource:
        driverClassName: "@flywayDriver@"
        url: "@flywayUrl@"
        username: "@flywayUser@"
        password: "@flywayPassword@"

    jpa:
        generate-ddl: false
        hibernate:
            ddl-auto: validate
            hbm2ddl:
              auto: validate
        properties:
            hibernate:
                hbm2ddl:
                    auto: validate
    resources:
        cachePeriod: 31556926
#        staticPathPattern: /**
#        staticLocations: [ "classpath:/META-INF/resources/", "classpath:/resources/", "classpath:/static/", "classpath:/public/" ]

flyway:
    baseline-on-migrate: true
    locations: "@flywayLocations@"

---

spring:
    profiles: dev
#    h2:
#        console:
#            enabled: true

security:
    user:
        name: admin
        password: admin
        role: ADMIN

---

spring:
    profiles: test

# @see org.springframework.boot.autoconfigure.security.SecurityProperties.java
security:
    user:
        name: admin
        password: admin
        role: ADMIN

server:
    port: 0

---

spring:
    profiles: demo

---

spring:
    profiles: prod
